version: "3.3"

services:
  #####################################################
  # PROXY
  #####################################################
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: ${COMPOSE_PROJECT_NAME}.nginx
    links:
      - api
      - db
      - bus
      - polytron
      - reactron

  #####################################################
  # Web Apps
  #####################################################

  ## WebComponents w/ Polymer
  polytron:
    image: ${COMPOSE_PROJECT_NAME}/polytron
    container_name: ${COMPOSE_PROJECT_NAME}.polytron
  ## ReactDOM w/ NextJS
  reactron:
    image: ${COMPOSE_PROJECT_NAME}/reactron
    container_name: ${COMPOSE_PROJECT_NAME}.reactron

  elelm:
    image: ${COMPOSE_PROJECT_NAME}/elelm
    container_name: ${COMPOSE_PROJECT_NAME}.elelm

  #####################################################
  # DB Storage
  #####################################################
  db:
    image: ${COMPOSE_PROJECT_NAME}/db
    container_name: ${COMPOSE_PROJECT_NAME}.db
  #####################################################
  # Message Broker
  #####################################################
  bus:
    image: ${COMPOSE_PROJECT_NAME}/bus
    build: ${BUS_PATH}
    container_name: ${COMPOSE_PROJECT_NAME}.bus
  #####################################################
  # EXPRESS API GATEWAY
  #####################################################
  api:
    image: ${COMPOSE_PROJECT_NAME}/api
    container_name: ${COMPOSE_PROJECT_NAME}.api

  ##################################################
  ## Micro-Services
  ##################################################
  # gRPC server
  service-grpc:
    image: ${COMPOSE_PROJECT_NAME}/service-grpc
    container_name: ${COMPOSE_PROJECT_NAME}.service-grpc
    restart: unless-stopped

  # http server
  service-http:
    image: ${COMPOSE_PROJECT_NAME}/service-http
    container_name: ${COMPOSE_PROJECT_NAME}.service-http

