version: "3"

networks:
  sinergy-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

## TODO
volumes:
  db_data: {}
  logs_data: {}
  packages_data: {}

services:
  # Proxy
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: sinergy-nginx-proxy
    links:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${ROOT_PATH}/data/logs/nginx/:/var/log/nginx/
      - ${ROOT_PATH}/configuration/nginx/vhost.d/:/etc/nginx/vhost.d/
    networks:
     - sinergy-net
    environment:
      DEFAULT_HOST: sinergy.ing.net


  ## Dashboard
  web:
    image: sinergy/web
    container_name: sinergy-web
    restart: always
    build: ${WEB_SRV}
    command: yarn start:dev
    volumes:
      - ${WEB_SRV}/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      sinergy-net:
        #ipv4_address: 172.28.1.4
    env_file:
      - ${WEB_SRV}/.env
